# Generated by Django 5.2.7 on 2026-07-02 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_badge_profile_about_profile_cover_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='name',
        ),
        migrations.AddField(
            model_name='badge',
            name='color',
            field=models.CharField(default='primary', max_length=30),
        ),
        migrations.AddField(
            model_name='badge',
            name='title',
            field=models.CharField(default='Top Contributor', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
